### ISSUE TITLE
Link to Xous Book?

### ISSUE THREAD

**Issue by bunnie** [betrusted-io/xous-book#1]
I was looking for a link to the Xous book, and google took me here.

And there is a section on the README which says "link to xous book", but it's not an actual link.

Even if the book isn't finalized, it might be good to make the draft searchable/discoverable, because there could be useful morsels in the book for others to read. I just checked, and the book isn't linked off of the Wiki or on the Xous README either...

**Comment by xobs** [comment]
Thanks for the suggestion! I added a link.
